version: '3.8'

services:
  comfyui:
#    build: .
    init: true
    container_name: removebg
    image: "nextgpu/removebg:1.0.0"
    ports:
      - "8188:8188"
    volumes:
      - "${PWD}/output:/home/user/app/output"
    environment:
      - CLI_ARGS=--output-directory /home/user/app/output
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
